context:
  name: DSSP
  version: "3.1.4"
  sha256: 496282b4b5defc55d111190ab9f1b615a9574a2f090e7cf5444521c747b272d4
  build_number: 0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/cmbi/${{ name|lower }}/archive/refs/tags/${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: ${{ build_number }}
  skip: win
  script: |
    set -exo pipefail
    
    ./autogen.sh
    
    # Avoid build errors with newer Clang versions
    export CXXFLAGS="${CXXFLAGS} -std=c++14 -O3"
    
    ./configure --prefix="${PREFIX}" \
                --disable-static \
                --enable-shared \
                --with-boost="${PREFIX}" \
                --with-boost-libdir="${PREFIX}/lib" \
                CXX="${CXX}" \
                CXXFLAGS="${CXXFLAGS}" \
                LDFLAGS="${LDFLAGS}"
    
    make -j${CPU_COUNT}
    
    # Run tests (including static analysis with cppcheck)
    make check
    
    make install
    
    mkdir -p $PREFIX/share/man/man1
    install -m 644 doc/mkdssp.1 $PREFIX/share/man/man1/

requirements:
  build:
    - ${{ compiler("cxx") }}
    - ${{ stdlib("c") }}
    - autoconf
    - automake
    - cppcheck
    - libtool
    - make
  host:
    - libboost-devel
    - bzip2
    - zlib
  run_exports:
    - ${{ pin_subpackage(name|lower, upper_bound="x") }}

tests:
  - script:
      - mkdssp --version
      - mkdssp --help || true


about:
  homepage: https://swift.cmbi.umcn.nl/gv/dssp
  repository: https://github.com/cmbi/dssp
  documentation: https://swift.cmbi.umcn.nl/gv/dssp
  license: BSL-1.0
  license_file: LICENSE_1_0.txt
  summary: "The DSSP building software"
  description: >
    The DSSP program was designed by Wolfgang Kabsch and Chris Sander to
    standardize secondary structure assignment. DSSP is a database of secondary
    structure assignments (and much more) for all protein entries in the Protein
    Data Bank (PDB). DSSP is also the program that calculates DSSP entries from
    PDB entries. DSSP does not predict secondary structure.
    
extra:
  recipe-maintainers:
    - eunos-1128
    - padix-key
